// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sidecar/mexc/pushdata_v3_api_wrapper.proto

package proto

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type PushDataV3ApiWrapper struct {
	Channel string `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	// Types that are valid to be assigned to Body:
	//	*PushDataV3ApiWrapper_PublicMiniTicker
	Body isPushDataV3ApiWrapper_Body `protobuf_oneof:"body"`
	// Types that are valid to be assigned to XSymbol:
	//	*PushDataV3ApiWrapper_Symbol
	XSymbol isPushDataV3ApiWrapper_XSymbol `protobuf_oneof:"_symbol"`
	// Types that are valid to be assigned to XSymbolId:
	//	*PushDataV3ApiWrapper_SymbolId
	XSymbolId isPushDataV3ApiWrapper_XSymbolId `protobuf_oneof:"_symbolId"`
	// Types that are valid to be assigned to XCreateTime:
	//	*PushDataV3ApiWrapper_CreateTime
	XCreateTime isPushDataV3ApiWrapper_XCreateTime `protobuf_oneof:"_createTime"`
	// Types that are valid to be assigned to XSendTime:
	//	*PushDataV3ApiWrapper_SendTime
	XSendTime isPushDataV3ApiWrapper_XSendTime `protobuf_oneof:"_sendTime"`
}

func (m *PushDataV3ApiWrapper) Reset()         { *m = PushDataV3ApiWrapper{} }
func (m *PushDataV3ApiWrapper) String() string { return proto.CompactTextString(m) }
func (*PushDataV3ApiWrapper) ProtoMessage()    {}
func (*PushDataV3ApiWrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c252293ef05ba7d, []int{0}
}
func (m *PushDataV3ApiWrapper) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PushDataV3ApiWrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PushDataV3ApiWrapper.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PushDataV3ApiWrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushDataV3ApiWrapper.Merge(m, src)
}
func (m *PushDataV3ApiWrapper) XXX_Size() int {
	return m.Size()
}
func (m *PushDataV3ApiWrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_PushDataV3ApiWrapper.DiscardUnknown(m)
}

var xxx_messageInfo_PushDataV3ApiWrapper proto.InternalMessageInfo

type isPushDataV3ApiWrapper_Body interface {
	isPushDataV3ApiWrapper_Body()
	MarshalTo([]byte) (int, error)
	Size() int
}
type isPushDataV3ApiWrapper_XSymbol interface {
	isPushDataV3ApiWrapper_XSymbol()
	MarshalTo([]byte) (int, error)
	Size() int
}
type isPushDataV3ApiWrapper_XSymbolId interface {
	isPushDataV3ApiWrapper_XSymbolId()
	MarshalTo([]byte) (int, error)
	Size() int
}
type isPushDataV3ApiWrapper_XCreateTime interface {
	isPushDataV3ApiWrapper_XCreateTime()
	MarshalTo([]byte) (int, error)
	Size() int
}
type isPushDataV3ApiWrapper_XSendTime interface {
	isPushDataV3ApiWrapper_XSendTime()
	MarshalTo([]byte) (int, error)
	Size() int
}

type PushDataV3ApiWrapper_PublicMiniTicker struct {
	PublicMiniTicker *PublicMiniTickerV3Api `protobuf:"bytes,309,opt,name=publicMiniTicker,proto3,oneof" json:"publicMiniTicker,omitempty"`
}
type PushDataV3ApiWrapper_Symbol struct {
	Symbol string `protobuf:"bytes,3,opt,name=symbol,proto3,oneof" json:"symbol,omitempty"`
}
type PushDataV3ApiWrapper_SymbolId struct {
	SymbolId string `protobuf:"bytes,4,opt,name=symbolId,proto3,oneof" json:"symbolId,omitempty"`
}
type PushDataV3ApiWrapper_CreateTime struct {
	CreateTime int64 `protobuf:"varint,5,opt,name=createTime,proto3,oneof" json:"createTime,omitempty"`
}
type PushDataV3ApiWrapper_SendTime struct {
	SendTime int64 `protobuf:"varint,6,opt,name=sendTime,proto3,oneof" json:"sendTime,omitempty"`
}

func (*PushDataV3ApiWrapper_PublicMiniTicker) isPushDataV3ApiWrapper_Body()  {}
func (*PushDataV3ApiWrapper_Symbol) isPushDataV3ApiWrapper_XSymbol()         {}
func (*PushDataV3ApiWrapper_SymbolId) isPushDataV3ApiWrapper_XSymbolId()     {}
func (*PushDataV3ApiWrapper_CreateTime) isPushDataV3ApiWrapper_XCreateTime() {}
func (*PushDataV3ApiWrapper_SendTime) isPushDataV3ApiWrapper_XSendTime()     {}

func (m *PushDataV3ApiWrapper) GetBody() isPushDataV3ApiWrapper_Body {
	if m != nil {
		return m.Body
	}
	return nil
}
func (m *PushDataV3ApiWrapper) GetXSymbol() isPushDataV3ApiWrapper_XSymbol {
	if m != nil {
		return m.XSymbol
	}
	return nil
}
func (m *PushDataV3ApiWrapper) GetXSymbolId() isPushDataV3ApiWrapper_XSymbolId {
	if m != nil {
		return m.XSymbolId
	}
	return nil
}
func (m *PushDataV3ApiWrapper) GetXCreateTime() isPushDataV3ApiWrapper_XCreateTime {
	if m != nil {
		return m.XCreateTime
	}
	return nil
}
func (m *PushDataV3ApiWrapper) GetXSendTime() isPushDataV3ApiWrapper_XSendTime {
	if m != nil {
		return m.XSendTime
	}
	return nil
}

func (m *PushDataV3ApiWrapper) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *PushDataV3ApiWrapper) GetPublicMiniTicker() *PublicMiniTickerV3Api {
	if x, ok := m.GetBody().(*PushDataV3ApiWrapper_PublicMiniTicker); ok {
		return x.PublicMiniTicker
	}
	return nil
}

func (m *PushDataV3ApiWrapper) GetSymbol() string {
	if x, ok := m.GetXSymbol().(*PushDataV3ApiWrapper_Symbol); ok {
		return x.Symbol
	}
	return ""
}

func (m *PushDataV3ApiWrapper) GetSymbolId() string {
	if x, ok := m.GetXSymbolId().(*PushDataV3ApiWrapper_SymbolId); ok {
		return x.SymbolId
	}
	return ""
}

func (m *PushDataV3ApiWrapper) GetCreateTime() int64 {
	if x, ok := m.GetXCreateTime().(*PushDataV3ApiWrapper_CreateTime); ok {
		return x.CreateTime
	}
	return 0
}

func (m *PushDataV3ApiWrapper) GetSendTime() int64 {
	if x, ok := m.GetXSendTime().(*PushDataV3ApiWrapper_SendTime); ok {
		return x.SendTime
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*PushDataV3ApiWrapper) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*PushDataV3ApiWrapper_PublicMiniTicker)(nil),
		(*PushDataV3ApiWrapper_Symbol)(nil),
		(*PushDataV3ApiWrapper_SymbolId)(nil),
		(*PushDataV3ApiWrapper_CreateTime)(nil),
		(*PushDataV3ApiWrapper_SendTime)(nil),
	}
}

func init() {
	proto.RegisterType((*PushDataV3ApiWrapper)(nil), "sidecar.mexc.PushDataV3ApiWrapper")
}

func init() {
	proto.RegisterFile("sidecar/mexc/pushdata_v3_api_wrapper.proto", fileDescriptor_2c252293ef05ba7d)
}

var fileDescriptor_2c252293ef05ba7d = []byte{
	// 339 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xbf, 0x4e, 0x02, 0x41,
	0x18, 0xc4, 0x6f, 0x01, 0x0f, 0x59, 0x34, 0x31, 0x17, 0x8b, 0x8b, 0x24, 0x07, 0x91, 0x86, 0x58,
	0x1c, 0x89, 0x54, 0x96, 0x5e, 0x2c, 0xb0, 0x30, 0x21, 0x1b, 0xa2, 0x89, 0xcd, 0x65, 0x6f, 0xf7,
	0x4b, 0xd8, 0x00, 0xb7, 0x9b, 0xdd, 0x03, 0xe4, 0x0d, 0x28, 0x7d, 0x19, 0xdf, 0xc0, 0xc2, 0x92,
	0xd2, 0xd2, 0xc0, 0x8b, 0x98, 0xfb, 0x03, 0xa2, 0x56, 0x9b, 0x99, 0xfd, 0xcd, 0x4c, 0xf1, 0xe1,
	0x2b, 0x23, 0x38, 0x30, 0xaa, 0xbb, 0x53, 0x78, 0x61, 0x5d, 0x35, 0x33, 0x23, 0x4e, 0x13, 0x1a,
	0xce, 0x7b, 0x21, 0x55, 0x22, 0x5c, 0x68, 0xaa, 0x14, 0x68, 0x5f, 0x69, 0x99, 0x48, 0xe7, 0xa4,
	0x60, 0xfd, 0x94, 0xbd, 0x68, 0xfc, 0x4a, 0x6a, 0x30, 0x4a, 0xc6, 0x06, 0x72, 0xf4, 0xf2, 0xbd,
	0x84, 0xcf, 0x07, 0x33, 0x33, 0xba, 0xa3, 0x09, 0x7d, 0xec, 0xdd, 0x2a, 0xf1, 0x94, 0x37, 0x39,
	0x2e, 0xae, 0xb2, 0x11, 0x8d, 0x63, 0x98, 0xb8, 0xa8, 0x85, 0x3a, 0x35, 0xb2, 0x93, 0x0e, 0xc1,
	0x67, 0x6a, 0x16, 0x4d, 0x04, 0x7b, 0x10, 0xb1, 0x18, 0x0a, 0x36, 0x06, 0xed, 0xbe, 0x95, 0x5a,
	0xa8, 0x53, 0xbf, 0x6e, 0xfb, 0x87, 0xcb, 0xfe, 0xe0, 0x0f, 0x96, 0x0d, 0xf4, 0x2d, 0xf2, 0x2f,
	0xef, 0x34, 0xb0, 0x6d, 0x96, 0xd3, 0x48, 0x4e, 0xdc, 0x72, 0x3a, 0xd6, 0x47, 0xa4, 0xd0, 0x2b,
	0x84, 0x9c, 0x26, 0x3e, 0xce, 0xc5, 0x3d, 0x77, 0x2b, 0xd9, 0x77, 0x89, 0xec, 0x9d, 0x14, 0x68,
	0x63, 0xcc, 0x34, 0xd0, 0x04, 0x86, 0x62, 0x0a, 0xee, 0x51, 0x0b, 0x75, 0xca, 0xfd, 0x32, 0x39,
	0xf0, 0x76, 0x2d, 0x10, 0xf3, 0x0c, 0xb1, 0x33, 0xa4, 0x42, 0xf6, 0xce, 0x0a, 0xa1, 0xc0, 0xc6,
	0x95, 0x48, 0xf2, 0x65, 0x50, 0xc3, 0xd5, 0x30, 0x6f, 0x0f, 0xea, 0xb8, 0x16, 0xee, 0x86, 0x82,
	0x53, 0x5c, 0x0f, 0x7f, 0x2a, 0xf3, 0xbf, 0x22, 0x1e, 0xdc, 0x7c, 0x6c, 0x3c, 0xb4, 0xde, 0x78,
	0xe8, 0x6b, 0xe3, 0xa1, 0xd7, 0xad, 0x67, 0xad, 0xb7, 0x9e, 0xf5, 0xb9, 0xf5, 0xac, 0xe7, 0xa6,
	0xd2, 0x72, 0x2e, 0x38, 0x68, 0xd3, 0x5d, 0x40, 0x64, 0x24, 0x1b, 0x43, 0x62, 0x8a, 0x23, 0xa6,
	0x17, 0x88, 0xec, 0xec, 0xe9, 0x7d, 0x07, 0x00, 0x00, 0xff, 0xff, 0x61, 0x63, 0x00, 0x19, 0xe1,
	0x01, 0x00, 0x00,
}

func (m *PushDataV3ApiWrapper) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PushDataV3ApiWrapper) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PushDataV3ApiWrapper) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Body != nil {
		{
			size := m.Body.Size()
			i -= size
			if _, err := m.Body.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	if m.XSendTime != nil {
		{
			size := m.XSendTime.Size()
			i -= size
			if _, err := m.XSendTime.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	if m.XCreateTime != nil {
		{
			size := m.XCreateTime.Size()
			i -= size
			if _, err := m.XCreateTime.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	if m.XSymbolId != nil {
		{
			size := m.XSymbolId.Size()
			i -= size
			if _, err := m.XSymbolId.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	if m.XSymbol != nil {
		{
			size := m.XSymbol.Size()
			i -= size
			if _, err := m.XSymbol.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	if len(m.Channel) > 0 {
		i -= len(m.Channel)
		copy(dAtA[i:], m.Channel)
		i = encodeVarintPushdataV3ApiWrapper(dAtA, i, uint64(len(m.Channel)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PushDataV3ApiWrapper_Symbol) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PushDataV3ApiWrapper_Symbol) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	i -= len(m.Symbol)
	copy(dAtA[i:], m.Symbol)
	i = encodeVarintPushdataV3ApiWrapper(dAtA, i, uint64(len(m.Symbol)))
	i--
	dAtA[i] = 0x1a
	return len(dAtA) - i, nil
}
func (m *PushDataV3ApiWrapper_SymbolId) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PushDataV3ApiWrapper_SymbolId) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	i -= len(m.SymbolId)
	copy(dAtA[i:], m.SymbolId)
	i = encodeVarintPushdataV3ApiWrapper(dAtA, i, uint64(len(m.SymbolId)))
	i--
	dAtA[i] = 0x22
	return len(dAtA) - i, nil
}
func (m *PushDataV3ApiWrapper_CreateTime) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PushDataV3ApiWrapper_CreateTime) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	i = encodeVarintPushdataV3ApiWrapper(dAtA, i, uint64(m.CreateTime))
	i--
	dAtA[i] = 0x28
	return len(dAtA) - i, nil
}
func (m *PushDataV3ApiWrapper_SendTime) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PushDataV3ApiWrapper_SendTime) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	i = encodeVarintPushdataV3ApiWrapper(dAtA, i, uint64(m.SendTime))
	i--
	dAtA[i] = 0x30
	return len(dAtA) - i, nil
}
func (m *PushDataV3ApiWrapper_PublicMiniTicker) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PushDataV3ApiWrapper_PublicMiniTicker) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.PublicMiniTicker != nil {
		{
			size, err := m.PublicMiniTicker.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPushdataV3ApiWrapper(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x13
		i--
		dAtA[i] = 0xaa
	}
	return len(dAtA) - i, nil
}
func encodeVarintPushdataV3ApiWrapper(dAtA []byte, offset int, v uint64) int {
	offset -= sovPushdataV3ApiWrapper(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *PushDataV3ApiWrapper) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Channel)
	if l > 0 {
		n += 1 + l + sovPushdataV3ApiWrapper(uint64(l))
	}
	if m.XSymbol != nil {
		n += m.XSymbol.Size()
	}
	if m.XSymbolId != nil {
		n += m.XSymbolId.Size()
	}
	if m.XCreateTime != nil {
		n += m.XCreateTime.Size()
	}
	if m.XSendTime != nil {
		n += m.XSendTime.Size()
	}
	if m.Body != nil {
		n += m.Body.Size()
	}
	return n
}

func (m *PushDataV3ApiWrapper_Symbol) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Symbol)
	n += 1 + l + sovPushdataV3ApiWrapper(uint64(l))
	return n
}
func (m *PushDataV3ApiWrapper_SymbolId) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SymbolId)
	n += 1 + l + sovPushdataV3ApiWrapper(uint64(l))
	return n
}
func (m *PushDataV3ApiWrapper_CreateTime) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovPushdataV3ApiWrapper(uint64(m.CreateTime))
	return n
}
func (m *PushDataV3ApiWrapper_SendTime) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovPushdataV3ApiWrapper(uint64(m.SendTime))
	return n
}
func (m *PushDataV3ApiWrapper_PublicMiniTicker) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PublicMiniTicker != nil {
		l = m.PublicMiniTicker.Size()
		n += 2 + l + sovPushdataV3ApiWrapper(uint64(l))
	}
	return n
}

func sovPushdataV3ApiWrapper(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPushdataV3ApiWrapper(x uint64) (n int) {
	return sovPushdataV3ApiWrapper(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *PushDataV3ApiWrapper) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPushdataV3ApiWrapper
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PushDataV3ApiWrapper: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PushDataV3ApiWrapper: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Channel", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPushdataV3ApiWrapper
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPushdataV3ApiWrapper
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPushdataV3ApiWrapper
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Channel = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Symbol", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPushdataV3ApiWrapper
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPushdataV3ApiWrapper
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPushdataV3ApiWrapper
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.XSymbol = &PushDataV3ApiWrapper_Symbol{string(dAtA[iNdEx:postIndex])}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SymbolId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPushdataV3ApiWrapper
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPushdataV3ApiWrapper
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPushdataV3ApiWrapper
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.XSymbolId = &PushDataV3ApiWrapper_SymbolId{string(dAtA[iNdEx:postIndex])}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreateTime", wireType)
			}
			var v int64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPushdataV3ApiWrapper
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.XCreateTime = &PushDataV3ApiWrapper_CreateTime{v}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SendTime", wireType)
			}
			var v int64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPushdataV3ApiWrapper
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.XSendTime = &PushDataV3ApiWrapper_SendTime{v}
		case 309:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PublicMiniTicker", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPushdataV3ApiWrapper
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPushdataV3ApiWrapper
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPushdataV3ApiWrapper
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &PublicMiniTickerV3Api{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Body = &PushDataV3ApiWrapper_PublicMiniTicker{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPushdataV3ApiWrapper(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPushdataV3ApiWrapper
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPushdataV3ApiWrapper(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPushdataV3ApiWrapper
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPushdataV3ApiWrapper
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPushdataV3ApiWrapper
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPushdataV3ApiWrapper
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPushdataV3ApiWrapper
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPushdataV3ApiWrapper
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPushdataV3ApiWrapper        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPushdataV3ApiWrapper          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPushdataV3ApiWrapper = fmt.Errorf("proto: unexpected end of group")
)
