// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sidecar/mexc/response.proto

package proto

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type PublicMiniTickerV3Api struct {
	Symbol             string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Price              string `protobuf:"bytes,2,opt,name=price,proto3" json:"price,omitempty"`
	Rate               string `protobuf:"bytes,3,opt,name=rate,proto3" json:"rate,omitempty"`
	ZonedRate          string `protobuf:"bytes,4,opt,name=zonedRate,proto3" json:"zonedRate,omitempty"`
	High               string `protobuf:"bytes,5,opt,name=high,proto3" json:"high,omitempty"`
	Low                string `protobuf:"bytes,6,opt,name=low,proto3" json:"low,omitempty"`
	Volume             string `protobuf:"bytes,7,opt,name=volume,proto3" json:"volume,omitempty"`
	Quantity           string `protobuf:"bytes,8,opt,name=quantity,proto3" json:"quantity,omitempty"`
	LastCloseRate      string `protobuf:"bytes,9,opt,name=lastCloseRate,proto3" json:"lastCloseRate,omitempty"`
	LastCloseZonedRate string `protobuf:"bytes,10,opt,name=lastCloseZonedRate,proto3" json:"lastCloseZonedRate,omitempty"`
	LastCloseHigh      string `protobuf:"bytes,11,opt,name=lastCloseHigh,proto3" json:"lastCloseHigh,omitempty"`
	LastCloseLow       string `protobuf:"bytes,12,opt,name=lastCloseLow,proto3" json:"lastCloseLow,omitempty"`
}

func (m *PublicMiniTickerV3Api) Reset()         { *m = PublicMiniTickerV3Api{} }
func (m *PublicMiniTickerV3Api) String() string { return proto.CompactTextString(m) }
func (*PublicMiniTickerV3Api) ProtoMessage()    {}
func (*PublicMiniTickerV3Api) Descriptor() ([]byte, []int) {
	return fileDescriptor_121ff60533c9bf8e, []int{0}
}
func (m *PublicMiniTickerV3Api) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PublicMiniTickerV3Api) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PublicMiniTickerV3Api.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PublicMiniTickerV3Api) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublicMiniTickerV3Api.Merge(m, src)
}
func (m *PublicMiniTickerV3Api) XXX_Size() int {
	return m.Size()
}
func (m *PublicMiniTickerV3Api) XXX_DiscardUnknown() {
	xxx_messageInfo_PublicMiniTickerV3Api.DiscardUnknown(m)
}

var xxx_messageInfo_PublicMiniTickerV3Api proto.InternalMessageInfo

func (m *PublicMiniTickerV3Api) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *PublicMiniTickerV3Api) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *PublicMiniTickerV3Api) GetRate() string {
	if m != nil {
		return m.Rate
	}
	return ""
}

func (m *PublicMiniTickerV3Api) GetZonedRate() string {
	if m != nil {
		return m.ZonedRate
	}
	return ""
}

func (m *PublicMiniTickerV3Api) GetHigh() string {
	if m != nil {
		return m.High
	}
	return ""
}

func (m *PublicMiniTickerV3Api) GetLow() string {
	if m != nil {
		return m.Low
	}
	return ""
}

func (m *PublicMiniTickerV3Api) GetVolume() string {
	if m != nil {
		return m.Volume
	}
	return ""
}

func (m *PublicMiniTickerV3Api) GetQuantity() string {
	if m != nil {
		return m.Quantity
	}
	return ""
}

func (m *PublicMiniTickerV3Api) GetLastCloseRate() string {
	if m != nil {
		return m.LastCloseRate
	}
	return ""
}

func (m *PublicMiniTickerV3Api) GetLastCloseZonedRate() string {
	if m != nil {
		return m.LastCloseZonedRate
	}
	return ""
}

func (m *PublicMiniTickerV3Api) GetLastCloseHigh() string {
	if m != nil {
		return m.LastCloseHigh
	}
	return ""
}

func (m *PublicMiniTickerV3Api) GetLastCloseLow() string {
	if m != nil {
		return m.LastCloseLow
	}
	return ""
}

func init() {
	proto.RegisterType((*PublicMiniTickerV3Api)(nil), "sidecar.mexc.PublicMiniTickerV3Api")
}

func init() { proto.RegisterFile("sidecar/mexc/response.proto", fileDescriptor_121ff60533c9bf8e) }

var fileDescriptor_121ff60533c9bf8e = []byte{
	// 318 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x3f, 0x4f, 0x32, 0x41,
	0x10, 0xc6, 0x39, 0xfe, 0xbd, 0x30, 0x2f, 0x26, 0x66, 0xa2, 0x66, 0xa3, 0xe6, 0x34, 0xc4, 0xc2,
	0x0a, 0x0a, 0x2a, 0x4b, 0xb5, 0xb1, 0xd0, 0xc4, 0x10, 0x63, 0x41, 0x77, 0x77, 0x4c, 0x64, 0xc3,
	0x72, 0x7b, 0xee, 0x2e, 0x20, 0x7e, 0x0a, 0x3f, 0x96, 0x25, 0xa5, 0xa5, 0x81, 0x4f, 0xe0, 0x37,
	0x30, 0x3b, 0x47, 0xce, 0x60, 0xac, 0x76, 0x9e, 0xdf, 0x33, 0x33, 0xfb, 0x24, 0x03, 0x47, 0x56,
	0x0e, 0x29, 0x89, 0x4c, 0x77, 0x42, 0x2f, 0x49, 0xd7, 0x90, 0xcd, 0x74, 0x6a, 0xa9, 0x93, 0x19,
	0xed, 0x34, 0xb6, 0x36, 0x66, 0xc7, 0x9b, 0xed, 0xaf, 0x32, 0xec, 0xdf, 0x4f, 0x63, 0x25, 0x93,
	0x3b, 0x99, 0xca, 0x07, 0x99, 0x8c, 0xc9, 0x3c, 0xf6, 0x2e, 0x33, 0x89, 0x07, 0x50, 0xb7, 0x8b,
	0x49, 0xac, 0x95, 0x08, 0x4e, 0x83, 0xf3, 0x66, 0x7f, 0xa3, 0x70, 0x0f, 0x6a, 0x99, 0x91, 0x09,
	0x89, 0x32, 0xe3, 0x5c, 0x20, 0x42, 0xd5, 0x44, 0x8e, 0x44, 0x85, 0x21, 0xd7, 0x78, 0x0c, 0xcd,
	0x57, 0x9d, 0xd2, 0xb0, 0xef, 0x8d, 0x2a, 0x1b, 0x3f, 0xc0, 0x4f, 0x8c, 0xe4, 0xd3, 0x48, 0xd4,
	0xf2, 0x09, 0x5f, 0xe3, 0x2e, 0x54, 0x94, 0x9e, 0x8b, 0x3a, 0x23, 0x5f, 0xfa, 0x14, 0x33, 0xad,
	0xa6, 0x13, 0x12, 0xff, 0xf2, 0x14, 0xb9, 0xc2, 0x43, 0x68, 0x3c, 0x4f, 0xa3, 0xd4, 0x49, 0xb7,
	0x10, 0x0d, 0x76, 0x0a, 0x8d, 0x67, 0xb0, 0xa3, 0x22, 0xeb, 0xae, 0x95, 0xb6, 0xc4, 0x7f, 0x37,
	0xb9, 0x61, 0x1b, 0x62, 0x07, 0xb0, 0x00, 0x83, 0x22, 0x26, 0x70, 0xeb, 0x1f, 0xce, 0xd6, 0xd6,
	0x1b, 0x1f, 0xfc, 0xff, 0xaf, 0xad, 0x1e, 0x62, 0x1b, 0x5a, 0x05, 0xb8, 0xd5, 0x73, 0xd1, 0xe2,
	0xa6, 0x2d, 0x76, 0x75, 0xf1, 0xbe, 0x0a, 0x83, 0xe5, 0x2a, 0x0c, 0x3e, 0x57, 0x61, 0xf0, 0xb6,
	0x0e, 0x4b, 0xcb, 0x75, 0x58, 0xfa, 0x58, 0x87, 0xa5, 0xc1, 0x49, 0x66, 0xf4, 0x4c, 0x0e, 0xc9,
	0xd8, 0xee, 0x9c, 0x62, 0xab, 0x93, 0x31, 0x39, 0x9b, 0x5f, 0x91, 0x8f, 0x17, 0xd7, 0xf9, 0xe9,
	0x7d, 0x07, 0x00, 0x00, 0xff, 0xff, 0x4d, 0x07, 0xa1, 0x4a, 0xe2, 0x01, 0x00, 0x00,
}

func (m *PublicMiniTickerV3Api) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PublicMiniTickerV3Api) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PublicMiniTickerV3Api) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.LastCloseLow) > 0 {
		i -= len(m.LastCloseLow)
		copy(dAtA[i:], m.LastCloseLow)
		i = encodeVarintResponse(dAtA, i, uint64(len(m.LastCloseLow)))
		i--
		dAtA[i] = 0x62
	}
	if len(m.LastCloseHigh) > 0 {
		i -= len(m.LastCloseHigh)
		copy(dAtA[i:], m.LastCloseHigh)
		i = encodeVarintResponse(dAtA, i, uint64(len(m.LastCloseHigh)))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.LastCloseZonedRate) > 0 {
		i -= len(m.LastCloseZonedRate)
		copy(dAtA[i:], m.LastCloseZonedRate)
		i = encodeVarintResponse(dAtA, i, uint64(len(m.LastCloseZonedRate)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.LastCloseRate) > 0 {
		i -= len(m.LastCloseRate)
		copy(dAtA[i:], m.LastCloseRate)
		i = encodeVarintResponse(dAtA, i, uint64(len(m.LastCloseRate)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.Quantity) > 0 {
		i -= len(m.Quantity)
		copy(dAtA[i:], m.Quantity)
		i = encodeVarintResponse(dAtA, i, uint64(len(m.Quantity)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.Volume) > 0 {
		i -= len(m.Volume)
		copy(dAtA[i:], m.Volume)
		i = encodeVarintResponse(dAtA, i, uint64(len(m.Volume)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Low) > 0 {
		i -= len(m.Low)
		copy(dAtA[i:], m.Low)
		i = encodeVarintResponse(dAtA, i, uint64(len(m.Low)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.High) > 0 {
		i -= len(m.High)
		copy(dAtA[i:], m.High)
		i = encodeVarintResponse(dAtA, i, uint64(len(m.High)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.ZonedRate) > 0 {
		i -= len(m.ZonedRate)
		copy(dAtA[i:], m.ZonedRate)
		i = encodeVarintResponse(dAtA, i, uint64(len(m.ZonedRate)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Rate) > 0 {
		i -= len(m.Rate)
		copy(dAtA[i:], m.Rate)
		i = encodeVarintResponse(dAtA, i, uint64(len(m.Rate)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Price) > 0 {
		i -= len(m.Price)
		copy(dAtA[i:], m.Price)
		i = encodeVarintResponse(dAtA, i, uint64(len(m.Price)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Symbol) > 0 {
		i -= len(m.Symbol)
		copy(dAtA[i:], m.Symbol)
		i = encodeVarintResponse(dAtA, i, uint64(len(m.Symbol)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintResponse(dAtA []byte, offset int, v uint64) int {
	offset -= sovResponse(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *PublicMiniTickerV3Api) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Symbol)
	if l > 0 {
		n += 1 + l + sovResponse(uint64(l))
	}
	l = len(m.Price)
	if l > 0 {
		n += 1 + l + sovResponse(uint64(l))
	}
	l = len(m.Rate)
	if l > 0 {
		n += 1 + l + sovResponse(uint64(l))
	}
	l = len(m.ZonedRate)
	if l > 0 {
		n += 1 + l + sovResponse(uint64(l))
	}
	l = len(m.High)
	if l > 0 {
		n += 1 + l + sovResponse(uint64(l))
	}
	l = len(m.Low)
	if l > 0 {
		n += 1 + l + sovResponse(uint64(l))
	}
	l = len(m.Volume)
	if l > 0 {
		n += 1 + l + sovResponse(uint64(l))
	}
	l = len(m.Quantity)
	if l > 0 {
		n += 1 + l + sovResponse(uint64(l))
	}
	l = len(m.LastCloseRate)
	if l > 0 {
		n += 1 + l + sovResponse(uint64(l))
	}
	l = len(m.LastCloseZonedRate)
	if l > 0 {
		n += 1 + l + sovResponse(uint64(l))
	}
	l = len(m.LastCloseHigh)
	if l > 0 {
		n += 1 + l + sovResponse(uint64(l))
	}
	l = len(m.LastCloseLow)
	if l > 0 {
		n += 1 + l + sovResponse(uint64(l))
	}
	return n
}

func sovResponse(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozResponse(x uint64) (n int) {
	return sovResponse(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *PublicMiniTickerV3Api) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowResponse
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PublicMiniTickerV3Api: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PublicMiniTickerV3Api: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Symbol", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthResponse
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthResponse
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Symbol = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthResponse
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthResponse
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Price = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthResponse
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthResponse
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Rate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ZonedRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthResponse
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthResponse
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ZonedRate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field High", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthResponse
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthResponse
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.High = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Low", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthResponse
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthResponse
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Low = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Volume", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthResponse
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthResponse
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Volume = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Quantity", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthResponse
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthResponse
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Quantity = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastCloseRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthResponse
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthResponse
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LastCloseRate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastCloseZonedRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthResponse
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthResponse
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LastCloseZonedRate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastCloseHigh", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthResponse
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthResponse
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LastCloseHigh = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastCloseLow", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthResponse
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthResponse
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LastCloseLow = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipResponse(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthResponse
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipResponse(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowResponse
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowResponse
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthResponse
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupResponse
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthResponse
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthResponse        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowResponse          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupResponse = fmt.Errorf("proto: unexpected end of group")
)
